site_name: vEDST Documentation

docs_dir: docs

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - md_in_html
  - toc:
      permalink: ÔÉÅ
nav:
  - 'index.md'
  - 'vEDST Application': 'https://edst.vfds.dev'

extra_css:
  - css/extra.css